name: Deploy To Server Ischool

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: echo "Build step for Pull Request"

    - name: Debug info
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Is pull request merged: ${{ github.event.pull_request.merged }}"


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request_target' && github.event.pull_request.merged)
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t curaweda/iscool .

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push your-dockerhub-username/your-app-name

    - name: Upload source code to Server Ischool
      run: |
        # Copy source code to EC2 instance
        scp -r * ubuntu@18.138.44.177:/home/ubuntu/ischool
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy to Server Ischool
      run: |
        # Transfer Docker Compose file to EC2 instance
        scp docker-compose.yml ubuntu@18.138.44.177:/home/ubuntu/ischool
        # SSH into EC2 instance, pull the latest Docker image, and run it
        ssh ubuntu@18.138.44.177 "docker-compose -f /home/ubuntu/ischool pull && docker-compose -f /home/ubuntu/ischool up -d"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
