name: Deploy To Server Ischool

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: echo "Build step for Pull Request"
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    
    - name: Debug info
      run: |
        echo "Nama event: ${{ github.event_name }}"
        echo "Apakah pull request digabungkan: ${{ github.event.pull_request.merged }}"
        
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Build Docker image
      run: docker build -t curaweda/iscool .
  
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Push Docker image
      run: docker push curaweda/iscool
  
    - name: Upload source code to Server Ischool
      run: |
        # Salin kode sumber ke instansi EC2
        scp -r * ubuntu@18.138.44.177:/home/ubuntu/ischool
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
    - name: Deploy to Server Ischool
      run: |
        # Transfer file Docker Compose ke instansi EC2
        scp docker-compose.yml ubuntu@18.138.44.177:/home/ubuntu/ischool
        # SSH ke instansi EC2, tarik gambar Docker terbaru, dan jalankan
        ssh ubuntu@18.138.44.177 "docker-compose -f /home/ubuntu/ischool/docker-compose.yml pull && docker-compose -f /home/ubuntu/ischool/docker-compose.yml up -d"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
