name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 62.72.57.9
          username: root
          password: Curaweda125@
          port: 22
          debug: true
          script: |
            cd production/Sade-Server-1
            git pull origin main
            npm i
            pm2 restart 0
