name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}         
          username: root
          key: ${{ secrets.PRIVATE_KEY }}    
          port: 22
          script: |
            cd ~/apps/ga-ci-cd-nodejs
            git pull origin master
            npm install --only=prod
            pm2 restart YoutubeApp
