name: Staging CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: SECRET

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          password: ${{secrets.STAGING_PASSWORD}}
          port: 22
          debug: true
          script: |
            cd staging/Sade-Server-1
            git pull origin development
            npm i
            npx sequelize db:migrate
            pm2 restart 0
